name: CDK Deploy on AWS

on:
    push:
        branches:
            - main
      
jobs:
    build:
        runs-on: ubuntu-latest
        environment: Production
        permissions:
            contents: read
            id-token: write
        defaults:
            run: 
                working-directory: ${{ vars.DIRECTORIO_CDK }}
        env:
            APP_NAME: ${{ vars.APP_NAME }}
            ACCOUNT_AWS: ${{ vars.ACCOUNT_AWS }}
            REGION_AWS: ${{ vars.REGION_AWS }}
            VPC_ID: ${{ vars.VPC_ID }}
            SUBNET_ID_1: ${{ vars.SUBNET_ID_1 }}
            SUBNET_ID_2: ${{ vars.SUBNET_ID_2 }}
            SUBNET_CIDR_1: ${{ vars.SUBNET_CIDR_1 }}
            SUBNET_CIDR_2: ${{ vars.SUBNET_CIDR_2 }}
            SUBNET_AZ_1: ${{ vars.SUBNET_AZ_1 }}
            SUBNET_AZ_2: ${{ vars.SUBNET_AZ_2 }}
            RDS_SECURITY_GROUP_ID: ${{ vars.RDS_SECURITY_GROUP_ID }}
            ROUTE_TABLE_ID: ${{ vars.ROUTE_TABLE_ID }}
            INSTANCE_TYPE: ${{ vars.INSTANCE_TYPE }}
            CERTIFICATE_ARN: ${{ vars.CERTIFICATE_ARN }}
            DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
            SUBDOMAIN_NAME: ${{ vars.SUBDOMAIN_NAME }}
            CERTBOT_EMAIL: ${{ vars.CERTBOT_EMAIL }}
            NOTIFICATION_EMAILS: ${{ vars.NOTIFICATION_EMAILS }}
        steps:
            - name: Checkout Repositorio
              uses: actions/checkout@v4
      
            - name: Instalar .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ vars.VERSION_DOTNET }}
      
            - name: Instalar Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ vars.VERSION_NODEJS }}
                  
            - name: Instalar AWS CDK
              run: npm install -g aws-cdk
      
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
              with:
                  aws-region: ${{ vars.REGION_AWS }}
                  role-to-assume: ${{ vars.ARN_GITHUB_ROLE }}
                  
            - name: CDK Synth
              run: cdk synth
              
            - name: CDK Diff
              run: cdk --app cdk.out diff
              
            - name: CDK Deploy
              run: cdk --app cdk.out deploy --require-approval never
          